# Generated by Django 4.2.30 on 2026-05-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×630 px', null=True, upload_to='upload-blog/'),
        ),
    ]
